### ISSUE TITLE
Can't find Load Project downloaded project zip 

### ISSUE THREAD

**Issue by doganc** [signumsoftware/framework#455]
Hi, download a new project, when i built project a have couple of errors,
how can i resolve this?

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "dotnet "C:\Users\dogan\.nuget\packages\signum.tsgenerator\3.0.0\build\Signum.TSGenerator.dll" "obj\x64\Debug\netcoreapp3.1\Signum.React.Extensions.dll" "C:\Users\dogan\source\repos\Signum\Extensions\Signum.React.Extensions\obj\SignumReferences.txt" "C:\Users\dogan\source\repos\Signum\Extensions\Signum.React.Extensions\obj\SignumContent.txt"" exited with code -532462766.	Signum.React.Extensions	C:\Users\dogan\.nuget\packages\signum.tsgenerator\3.0.0\build\Signum.TSGenerator.targets	5	
```
``` 
Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2769	Build:No overload matches this call.	Signum.React	C:\Users\dogan\source\repos\Signum\Framework\Signum.React\Scripts\Components\Typeahead.tsx	249	
```

Thanks for all

**Comment by MehdyKarimpour** [comment]
Hi DoganC,
Thank you for consider using the framework.

1. Which version of VS are you using?
2. Which version of TS SDK did you install?

We prefer using VS 2019 Community Edition 16.4.5.

Also needs to install TS SDK 3.8.2, you can download it here

https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.typescript-382

Let us know if you have any questions.

best regards
mehdy

**Comment by olmobrutall** [comment]
About the TSGenerator, maybe you have more info in the Output panel. Can you paste what you have there?

**Comment by doganc** [comment]
Hi again, @MehdyKarimpour, @olmobrutall 
I'm using VS 2019 Enterprise 16.4.4
And my Output window details...

```
1>------ Build started: Project: Signum.React, Configuration: Debug x64 ------
2>------ Build started: Project: ObjesoftAppSignumV1.Terminal, Configuration: Debug x64 ------
2>Signum.MSBuildTask starting: obj\x64\Debug\netcoreapp3.1\ObjesoftAppSignumV1.Terminal.dll
2>Signum.MSBuildTask already processed: obj\x64\Debug\netcoreapp3.1\ObjesoftAppSignumV1.Terminal.dll
1>Starting SignumTSGenerator
2>ObjesoftAppSignumV1.Terminal -> C:\Users\dogan\source\repos\Signum\ObjesoftAppSignumV1.Terminal\bin\Debug\netcoreapp3.1\ObjesoftAppSignumV1.Terminal.dll
1>SignumTSGenerator already processed (154ms)
1>C:\Users\dogan\source\repos\Signum\Framework\Signum.React\Scripts\Components\Typeahead.tsx(249,10): error TS2769: Build:No overload matches this call.
1>Done building project "Signum.React.csproj" -- FAILED.
3>------ Build started: Project: Signum.React.Extensions, Configuration: Debug x64 ------
3>Starting SignumTSGenerator
3>Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\Users\dogan\source\repos\Signum\Framework\Signum.React\bin\x64\Debug\netcoreapp3.1\Signum.React.dll'.
3>File name: 'C:\Users\dogan\source\repos\Signum\Framework\Signum.React\bin\x64\Debug\netcoreapp3.1\Signum.React.dll'
3>   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
3>   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
3>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
3>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
3>   at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
3>   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
3>   at Signum.TSGenerator.PreloadingAssemblyResolver..ctor(String[] references)
3>   at Signum.TSGenerator.Program.Main(String[] args)
3>C:\Users\dogan\.nuget\packages\signum.tsgenerator\3.0.0\build\Signum.TSGenerator.targets(5,5): error MSB3073: The command "dotnet "C:\Users\dogan\.nuget\packages\signum.tsgenerator\3.0.0\build\Signum.TSGenerator.dll" "obj\x64\Debug\netcoreapp3.1\Signum.React.Extensions.dll" "C:\Users\dogan\source\repos\Signum\Extensions\Signum.React.Extensions\obj\SignumReferences.txt" "C:\Users\dogan\source\repos\Signum\Extensions\Signum.React.Extensions\obj\SignumContent.txt"" exited with code -532462766.
3>Done building project "Signum.React.Extensions.csproj" -- FAILED.
4>------ Build started: Project: ObjesoftAppSignumV1.React, Configuration: Debug x64 ------
4>Starting SignumTSGenerator
4>Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\Users\dogan\source\repos\Signum\Framework\Signum.React\bin\x64\Debug\netcoreapp3.1\Signum.React.dll'.
4>File name: 'C:\Users\dogan\source\repos\Signum\Framework\Signum.React\bin\x64\Debug\netcoreapp3.1\Signum.React.dll'
4>   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
4>   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
4>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
4>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
4>   at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
4>   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
4>   at Signum.TSGenerator.PreloadingAssemblyResolver..ctor(String[] references)
4>   at Signum.TSGenerator.Program.Main(String[] args)
4>C:\Users\dogan\.nuget\packages\signum.tsgenerator\3.0.0\build\Signum.TSGenerator.targets(5,5): error MSB3073: The command "dotnet "C:\Users\dogan\.nuget\packages\signum.tsgenerator\3.0.0\build\Signum.TSGenerator.dll" "obj\x64\Debug\netcoreapp3.1\ObjesoftAppSignumV1.React.dll" "C:\Users\dogan\source\repos\Signum\ObjesoftAppSignumV1.React\obj\SignumReferences.txt" "C:\Users\dogan\source\repos\Signum\ObjesoftAppSignumV1.React\obj\SignumContent.txt"" exited with code -532462766.
4>Done building project "ObjesoftAppSignumV1.React.csproj" -- FAILED.
========== Build: 1 succeeded, 3 failed, 9 up-to-date, 0 skipped ==========
```

**Comment by doganc** [comment]
Hi Again,
I try step by step build project, 
If i build Signum.React project, it has following errors,
```
1>------ Build started: Project: Signum.React, Configuration: Debug x64 ------
1>Starting SignumTSGenerator
1>SignumTSGenerator already processed (57ms)
1>C:\Users\dogan\source\repos\Signum\Framework\Signum.React\Scripts\Components\Typeahead.tsx(249,10): error TS2769: Build:No overload matches this call.
1>Done building project "Signum.React.csproj" -- FAILED.

**Comment by olmobrutall** [comment]
Do you have the latest TS? https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/

**Comment by MehdyKarimpour** [comment]
Or here https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.typescript-382

**Comment by doganc** [comment]
Hi, I've already installed TS latest version. and same error,
But when i open the project in Task Runner getting these error

```

ERROR in ./node_modules/react-transition-group/esm/CSSTransition.js
Module not found: Error: Can't resolve 'dom-helpers/addClass' in 'C:\Users\dogan\source\repos\Signum\ObjesoftAppSignumV1.React\node_modules\react-transition-group\esm'
 @ ./node_modules/react-transition-group/esm/CSSTransition.js 5:0-47 13:11-22
 @ ./node_modules/react-transition-group/esm/index.js
 @ ../Framework/Signum.React/Scripts/Frames/Notify.tsx
 @ ./App/Main.tsx
ERROR in ./node_modules/react-transition-group/esm/CSSTransition.js
Module not found: Error: Can't resolve 'dom-helpers/removeClass' in 'C:\Users\dogan\source\repos\Signum\ObjesoftAppSignumV1.React\node_modules\react-transition-group\esm'
 @ ./node_modules/react-transition-group/esm/CSSTransition.js 6:0-53 19:11-25
 @ ./node_modules/react-transition-group/esm/index.js
 @ ../Framework/Signum.React/Scripts/Frames/Notify.tsx
 @ ./App/Main.tsx

**Comment by MehdyKarimpour** [comment]
Please check your package.json file with Southwind one,
https://github.com/signumsoftware/southwind/blob/master/Southwind.React/package.json

**Comment by olmobrutall** [comment]
In Task Runner Explorer, check that you have run install for Signum.React, Signum.React.Extensions and YourApp.React (combo box on the left top corner of Task Runner Explorer)

**Comment by doganc** [comment]
Hi @olmobrutall 
Task Runner Results are 

```
C:\Users\dogan\source\repos\Signum\Framework\Signum.React> cmd.exe /c yarn upgrade 
yarn upgrade v1.22.4
[1/4] Resolving packages...
warning popper.js@1.15.0: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning react-bootstrap > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning react-bootstrap > react-overlays > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
success Saved 63 new dependencies.
info Direct dependencies
├─ @fortawesome/fontawesome-svg-core@1.2.27
├─ @fortawesome/free-brands-svg-icons@5.12.1
├─ @fortawesome/free-regular-svg-icons@5.12.1
├─ @fortawesome/free-solid-svg-icons@5.12.1
├─ @fortawesome/react-fontawesome@0.1.8
├─ @types/d3-scale-chromatic@1.3.1
├─ @types/d3@5.7.2
├─ @types/prop-types@15.7.3
├─ @types/query-string@5.1.0
├─ @types/react-dom@16.9.5
├─ @types/react-router-dom@5.1.3
├─ @types/react-router@5.1.4
├─ @types/react-transition-group@4.2.4
├─ @types/react-widgets@4.3.3
├─ @types/react@16.9.23
├─ moment@2.24.0
├─ numbro@2.1.2
├─ popper.js@1.15.0
├─ query-string@5.1.1
├─ react-bootstrap@1.0.0-beta.16
├─ react-dom@16.12.0
└─ react@16.12.0
info All dependencies
├─ @fortawesome/fontawesome-svg-core@1.2.27
├─ @fortawesome/free-brands-svg-icons@5.12.1
├─ @fortawesome/free-regular-svg-icons@5.12.1
├─ @fortawesome/free-solid-svg-icons@5.12.1
├─ @fortawesome/react-fontawesome@0.1.8
├─ @restart/context@2.1.4
├─ @restart/hooks@0.3.21
├─ @types/d3-array@1.2.7
├─ @types/d3-axis@1.0.12
├─ @types/d3-brush@1.1.0
├─ @types/d3-chord@1.0.9
├─ @types/d3-collection@1.0.8
├─ @types/d3-contour@1.3.0
├─ @types/d3-dispatch@1.0.7
├─ @types/d3-drag@1.2.3
├─ @types/d3-ease@1.0.9
├─ @types/d3-fetch@1.1.5
├─ @types/d3-force@1.2.1
├─ @types/d3-format@1.3.1
├─ @types/d3-geo@1.11.1
├─ @types/d3-hierarchy@1.1.6
├─ @types/d3-polygon@1.0.7
├─ @types/d3-quadtree@1.0.7
├─ @types/d3-random@1.1.2
├─ @types/d3-scale-chromatic@1.3.1
├─ @types/d3-scale@2.2.0
├─ @types/d3-shape@1.3.2
├─ @types/d3-time-format@2.1.1
├─ @types/d3-timer@1.0.9
├─ @types/d3-transition@1.1.6
├─ @types/d3-voronoi@1.1.9
├─ @types/d3-zoom@1.7.4
├─ @types/d3@5.7.2
├─ @types/prop-types@15.7.3
├─ @types/query-string@5.1.0
├─ @types/react-dom@16.9.5
├─ @types/react-router-dom@5.1.3
├─ @types/react-router@5.1.4
├─ @types/react-transition-group@4.2.4
├─ @types/react-widgets@4.3.3
├─ @types/react@16.9.23
├─ bignumber.js@8.1.1
├─ classnames@2.2.6
├─ csstype@2.6.9
├─ decode-uri-component@0.2.0
├─ dom-helpers@5.1.3
├─ js-tokens@4.0.0
├─ keycode@2.2.0
├─ moment@2.24.0
├─ numbro@2.1.2
├─ popper.js@1.15.0
├─ prop-types-extra@1.1.1
├─ query-string@5.1.1
├─ react-bootstrap@1.0.0-beta.16
├─ react-dom@16.12.0
├─ react-is@16.13.0
├─ react-lifecycles-compat@3.0.4
├─ react-overlays@2.1.1
├─ react-transition-group@4.3.0
├─ react@16.12.0
├─ regenerator-runtime@0.13.5
├─ scheduler@0.18.0
└─ strict-uri-encode@1.1.0
Done in 6.27s.
Process terminated with code 0.
C:\Users\dogan\source\repos\Signum\Framework\Signum.React> cmd.exe /c yarn install 
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.21s.
Process terminated with code 0.
C:\Users\dogan\source\repos\Signum\Extensions\Signum.React.Extensions> cmd.exe /c yarn install 
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.10s.
Process terminated with code 0.

**Comment by doganc** [comment]
I think this file has a problem.
 
```
1>------ Build started: Project: Signum.React, Configuration: Debug x64 ------
1>Starting SignumTSGenerator
1>SignumTSGenerator already processed (58ms)
1>C:\Users\dogan\source\repos\Signum\Framework\Signum.React\Scripts\Components\Typeahead.tsx(249,10): error TS2769: Build:No overload matches this call.
1>Done building project "Signum.React.csproj" -- FAILED.

**Comment by doganc** [comment]
Hi Again,
I drop my solution, and Download a new one from the web site DuplicateApplication,
Now, build is ok.
Database is also Ok.

**Comment by doganc** [comment]
But, I Want to start MyApp.React project, I'm getting this error,
```
Exception thrown: 'System.InvalidOperationException' in Signum.Utilities.dll
An exception of type 'System.InvalidOperationException' occurred in Signum.Utilities.dll but was not handled in user code
Sequence contains no CultureInfoEntity

**Comment by MehdyKarimpour** [comment]
Perfect! 
You can try to run C# migrations? ([YourAppName].Terminal => CS menu item)
This menu item creates necessary data on database

**Comment by doganc** [comment]
Hi @MehdyKarimpour 
I run the Terminal Project with  CS and Load options, after that i run my React project, i got this error,

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains no CultureInfoEntity
  Source=Signum.Utilities
  StackTrace:
   at Signum.Utilities.EnumerableUniqueExtensions.FirstEx[T](IEnumerable`1 collection) in C:\Users\dogan\source\repos\ObjeSoftSFV2\Framework\Signum.Utilities\Extensions\EnumerableExtensions.cs:line 268
   at Signum.React.Translation.CultureController.CurrentCulture() in C:\Users\dogan\source\repos\ObjeSoftSFV2\Extensions\Signum.React.Extensions\Translation\CulturesController.cs:line 43
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeActionMethodAsync>g__Logged|12_1>d.MoveNext()

**Comment by doganc** [comment]
Why is it so hard to start? or may be i don't know some hidden tricks. 
Sorry to disturb you, @MehdyKarimpour

**Comment by olmobrutall** [comment]
Try restarting IIS or making a tiny change in Starter.cs in React project and play again. .Net Core (opposed to .Net Framework) doesn't try to start again after an failed start. 

It'S hard to start because there are many technologies involved SQL, .Net Core, Typescript, React, yarn, all of them changing frequently so it's hard to keep the documentation up to date. 

Remember is an open source project and the people contributing to it of helping you are not getting any money for it. If you find changes in documentation or of any other kind that will make the starting experience better pull request are more than welcome.

**Comment by MehdyKarimpour** [comment]
Hi DoganC, 
Olmo is right but I can check it by AnyDesk if you want. My Skype id is live:mkarimpour_1

**Comment by doganc** [comment]
Hi @MehdyKarimpour , @olmobrutall 
Thanks for every think.
The Project is running. It's about Loading data.
