### ISSUE TITLE
CultureInfo exception

### ISSUE THREAD

**Issue by LauraRG** [signumsoftware/framework#69]
Hi!

We have a problem in our web application with CultureInfo entity when users try to register. This is the exception:

`The instance Portuguese is sealed and can not be modified`

And this is the trace:

```
at Signum.Entities.Modifiable.set_Modified(ModifiedState value)
   at Signum.Entities.ModifiableEntity.Set[T](T& field, T value, String automaticPropertyName)
   at Signum.Entities.Basics.CultureInfoEntity.PreSaving(Boolean& graphModified)
   at Signum.Engine.Saver.<>c__DisplayClass2_1.<Save>b__2(Modifiable m, Boolean& graphModified)
   at Signum.Entities.Reflection.GraphExplorer.PreSaving(Func'1 recreate, ModifyEntityEventHandler modifier)
   at Signum.Engine.Saver.Save(Entity[] entities)
   at Signum.Engine.Database.Save[T](T entity)
   at ....UserController.DoCreateUserAndLogin(...)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary'2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func'1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func'1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func'1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
```

We have registers like these in our database (from CultureInfo):

```
Portuguese (Portugal) | pt-PT | português (Potugal)
Portuguese | pt | português
```

Nevertheless, when we try to synchronize the database we always obtain this script:

```
UPDATE basics.CultureInfo SET 
  Ticks = 635858020893728000,
  Name = 'es-ES',
  NativeName = 'español (España, alfabetización internacional)',
  EnglishName = 'Spanish (Spain, International Sort)'
 WHERE ID = 3 AND Ticks = 635858020893728000
```

Do you have any idea about where is the problem?

Thank you!

**Comment by olmobrutall** [comment]
Hi! 

It looks like the values that .Net returns on CultureInfoEntity.PreSaving are unstable depending on the server version.

 I'm don't know of a good solution in this case, but you can add an if on the PreSaving to avoid assigning the fields if they are not null, or if the entity is not new. 

This will remove the problem. 

Regards.
